# Form implementation generated from reading ui file 'C:\Users\Masha\PycharmProjects\tech_sub\app\ui_from\auth_graf.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(398, 300)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(37, 15, 11))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 78, 43))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 178))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 15, 11))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 136, 76))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 178))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 178))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 178))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("XO Tahion")
        Form.setFont(font)
        self.pushButton_auth_in = QtWidgets.QPushButton(parent=Form)
        self.pushButton_auth_in.setGeometry(QtCore.QRect(130, 200, 141, 31))
        self.pushButton_auth_in.setObjectName("pushButton_auth_in")
        self.pushButton_reg_in_auth = QtWidgets.QPushButton(parent=Form)
        self.pushButton_reg_in_auth.setGeometry(QtCore.QRect(130, 250, 141, 31))
        self.pushButton_reg_in_auth.setObjectName("pushButton_reg_in_auth")
        self.label_auth = QtWidgets.QLabel(parent=Form)
        self.label_auth.setGeometry(QtCore.QRect(120, 20, 161, 31))
        self.label_auth.setObjectName("label_auth")
        self.lineEdit_auth_login = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_auth_login.setGeometry(QtCore.QRect(20, 80, 341, 31))
        self.lineEdit_auth_login.setObjectName("lineEdit_auth_login")
        self.lineEdit_aut_pass = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_aut_pass.setGeometry(QtCore.QRect(20, 150, 341, 31))
        self.lineEdit_aut_pass.setObjectName("lineEdit_aut_pass")
        self.label_auth_login = QtWidgets.QLabel(parent=Form)
        self.label_auth_login.setGeometry(QtCore.QRect(20, 60, 121, 21))
        self.label_auth_login.setObjectName("label_auth_login")
        self.label_auth_pass = QtWidgets.QLabel(parent=Form)
        self.label_auth_pass.setGeometry(QtCore.QRect(20, 130, 101, 16))
        self.label_auth_pass.setObjectName("label_auth_pass")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_auth_in.setText(_translate("Form", "Войти"))
        self.pushButton_reg_in_auth.setText(_translate("Form", "Зарегистрироваться"))
        self.label_auth.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">Авторизация</span></p></body></html>"))
        self.label_auth_login.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Введите логин:</span></p></body></html>"))
        self.label_auth_pass.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Введите пароль:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
