# Form implementation generated from reading ui file 'C:\Users\Masha\PycharmProjects\tech_sub\app\ui_from\reg_graf.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 342)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(37, 15, 11))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 178))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 15, 11))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 178))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 178))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 178))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        Form.setPalette(palette)
        self.label_reg_login = QtWidgets.QLabel(parent=Form)
        self.label_reg_login.setGeometry(QtCore.QRect(20, 50, 121, 21))
        self.label_reg_login.setObjectName("label_reg_login")
        self.lineEdit_reg_pass = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_reg_pass.setGeometry(QtCore.QRect(20, 210, 341, 31))
        self.lineEdit_reg_pass.setObjectName("lineEdit_reg_pass")
        self.label_reg_pass = QtWidgets.QLabel(parent=Form)
        self.label_reg_pass.setGeometry(QtCore.QRect(20, 190, 101, 16))
        self.label_reg_pass.setObjectName("label_reg_pass")
        self.lineEdit_reg_login = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_reg_login.setGeometry(QtCore.QRect(20, 70, 341, 31))
        self.lineEdit_reg_login.setObjectName("lineEdit_reg_login")
        self.pushButton_reg_in = QtWidgets.QPushButton(parent=Form)
        self.pushButton_reg_in.setGeometry(QtCore.QRect(120, 260, 141, 31))
        self.pushButton_reg_in.setObjectName("pushButton_reg_in")
        self.label_reg = QtWidgets.QLabel(parent=Form)
        self.label_reg.setGeometry(QtCore.QRect(130, 10, 161, 31))
        self.label_reg.setObjectName("label_reg")
        self.pushButton_reg_in_auth = QtWidgets.QPushButton(parent=Form)
        self.pushButton_reg_in_auth.setGeometry(QtCore.QRect(120, 300, 141, 31))
        self.pushButton_reg_in_auth.setObjectName("pushButton_reg_in_auth")
        self.lineEdit_reg_number = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_reg_number.setGeometry(QtCore.QRect(20, 140, 341, 31))
        self.lineEdit_reg_number.setObjectName("lineEdit_reg_number")
        self.label_reg_number = QtWidgets.QLabel(parent=Form)
        self.label_reg_number.setGeometry(QtCore.QRect(20, 120, 161, 21))
        self.label_reg_number.setObjectName("label_reg_number")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_reg_login.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Введите логин:</span></p></body></html>"))
        self.label_reg_pass.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Введите пароль:</span></p></body></html>"))
        self.pushButton_reg_in.setText(_translate("Form", "Зарегистрироваться"))
        self.label_reg.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">Регистрация</span></p><p><br/></p></body></html>"))
        self.pushButton_reg_in_auth.setText(_translate("Form", "Авторизоваться"))
        self.label_reg_number.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Введите номер телефона:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
