
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_admin_wind(object):
    def setupUi(self, admin_wind):
        admin_wind.setObjectName("admin_wind")
        admin_wind.resize(811, 536)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(121, 78, 40))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 179))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 136, 76))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 179))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(176, 136, 76))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 179))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 209, 179))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        admin_wind.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("XO Tahion")
        font.setPointSize(10)
        admin_wind.setFont(font)
        self.label_log_adm = QtWidgets.QLabel(parent=admin_wind)
        self.label_log_adm.setGeometry(QtCore.QRect(20, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("XO Tahion")
        font.setPointSize(12)
        self.label_log_adm.setFont(font)
        self.label_log_adm.setObjectName("label_log_adm")
        self.label_pass_adm = QtWidgets.QLabel(parent=admin_wind)
        self.label_pass_adm.setGeometry(QtCore.QRect(290, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("XO Tahion")
        font.setPointSize(12)
        self.label_pass_adm.setFont(font)
        self.label_pass_adm.setObjectName("label_pass_adm")
        self.label_role_adm = QtWidgets.QLabel(parent=admin_wind)
        self.label_role_adm.setGeometry(QtCore.QRect(560, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("XO Tahion")
        font.setPointSize(12)
        self.label_role_adm.setFont(font)
        self.label_role_adm.setObjectName("label_role_adm")
        self.lineEdit_log_adm = QtWidgets.QLineEdit(parent=admin_wind)
        self.lineEdit_log_adm.setGeometry(QtCore.QRect(20, 40, 201, 31))
        self.lineEdit_log_adm.setObjectName("lineEdit_log_adm")
        self.lineEdit_pass_adm = QtWidgets.QLineEdit(parent=admin_wind)
        self.lineEdit_pass_adm.setGeometry(QtCore.QRect(290, 40, 201, 31))
        self.lineEdit_pass_adm.setObjectName("lineEdit_pass_adm")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=admin_wind)
        self.lineEdit_3.setGeometry(QtCore.QRect(560, 40, 201, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.groupBox_users_adm = QtWidgets.QGroupBox(parent=admin_wind)
        self.groupBox_users_adm.setGeometry(QtCore.QRect(20, 160, 741, 341))
        self.groupBox_users_adm.setObjectName("groupBox_users_adm")
        self.btn_create_user_adm = QtWidgets.QPushButton(parent=admin_wind)
        self.btn_create_user_adm.setGeometry(QtCore.QRect(140, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("XO Tahion")
        font.setPointSize(12)
        self.btn_create_user_adm.setFont(font)
        self.btn_create_user_adm.setObjectName("btn_create_user_adm")
        self.btn_del_user_adm = QtWidgets.QPushButton(parent=admin_wind)
        self.btn_del_user_adm.setGeometry(QtCore.QRect(460, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("XO Tahion")
        font.setPointSize(12)
        self.btn_del_user_adm.setFont(font)
        self.btn_del_user_adm.setObjectName("btn_del_user_adm")

        self.retranslateUi(admin_wind)
        QtCore.QMetaObject.connectSlotsByName(admin_wind)

    def retranslateUi(self, admin_wind):
        _translate = QtCore.QCoreApplication.translate
        admin_wind.setWindowTitle(_translate("admin_wind", "Form"))
        self.label_log_adm.setText(_translate("admin_wind", "<html><head/><body><p><span style=\" font-size:12pt;\">Логин:</span></p></body></html>"))
        self.label_pass_adm.setText(_translate("admin_wind", "<html><head/><body><p><span style=\" font-size:12pt;\">Пароль:</span></p></body></html>"))
        self.label_role_adm.setText(_translate("admin_wind", "<html><head/><body><p><span style=\" font-size:12pt;\">Роль:</span></p></body></html>"))
        self.groupBox_users_adm.setTitle(_translate("admin_wind", "Список всех пользователей:"))
        self.btn_create_user_adm.setText(_translate("admin_wind", "Создать пользователя"))
        self.btn_del_user_adm.setText(_translate("admin_wind", "Удалить пользователя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    admin_wind = QtWidgets.QWidget()
    ui = Ui_admin_wind()
    ui.setupUi(admin_wind)
    admin_wind.show()
    sys.exit(app.exec())
